### ISSUE TITLE
Unknown configuration section "certificates"

### ISSUE THREAD

**Issue by AditiSharma77** [fredrikhgrelland/data-mesh#114]
When i m trying to do vagrant up so getting error related to certificate .

Vagrant:
* Unknown configuration section 'certificates'.

**Comment by zhenik** [comment]
I think lacking of [vagrant-certificates plugin](https://github.com/gfi-centre-ouest/vagrant-certificates)

**Comment by pdmthorsrud** [comment]
Did this get resolved, and can we close it? :) @zhenik, do you know? (asking you because Aditi is away for a little while)

**Comment by zhenik** [comment]
Waiting for answer from @AditiSharma77

**Comment by AditiSharma77** [comment]
sudo SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt vagrant plugin install vagrant-certificates
Working atm , so close this
