### ISSUE TITLE
remove or fix check for hue

### ISSUE THREAD

**Issue by fredrikhgrelland** [fredrikhgrelland/data-mesh#73]
https://github.com/fredrikhgrelland/data-mesh/blob/5ca83415872c48fdfb0b6eb0f7837cc5508385a4/resources/nomad-jobs/hue-connect.hcl#L41-L49

**Comment by m88614** [comment]
Nikita mentioned their API had some trouble. I don't have the reference, @zhenik, could you please provide it? (I couldn't find it in our chat)

**Comment by zhenik** [comment]
> Nikita mentioned their API had some trouble. I don't have the reference, @zhenik, could you please provide it? (I couldn't find it in our chat)

* [REST hue](https://docs.gethue.com/developer/api/) 

* [JIRA-1450. WIP](https://issues.cloudera.org/browse/HUE-1450)
