### ISSUE TITLE
Update doc: how to download/use box when behind transparent proxy

### ISSUE THREAD

**Issue by m88614** [fredrikhgrelland/data-mesh#83]
Eivind just tried data-mesh for the first time. Still getting the `SSL certificate` error. @fredrikhgrelland should this be fixed in `vagrant-hashistack`?
![image](https://user-images.githubusercontent.com/51820995/84644161-16c31a80-aeff-11ea-9138-7df9e6c09e7b.png)

**Comment by m88614** [comment]
I have just instructed him to download the box for now

**Comment by zhenik** [comment]
> I have just instructed him to download the box for now

The same happens to Aditi.

**Comment by fredrikhgrelland** [comment]
This is expected if you have not installed based on fredrikhgrelland/vagrant-hashistack `make install`

**Comment by fredrikhgrelland** [comment]
This is NOT a bug. Transparent proxy is making it hard. It will work anywhere but behind a MITM proxy.

**Comment by fredrikhgrelland** [comment]
Prefix: `SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt vagrant`

**Comment by fredrikhgrelland** [comment]
https://github.com/fredrikhgrelland/vagrant-hashistack/issues/43

**Comment by m88614** [comment]
Should've been closed by fredrikhgrelland/vagrant-hashistack#39, not sure why it wasn't.

Closing manually
