### ISSUE TITLE
MinIO OOM problems after running for a while

### ISSUE THREAD

**Issue by m88614** [fredrikhgrelland/data-mesh#85]
![image](https://user-images.githubusercontent.com/51820995/84739478-fc934600-afab-11ea-9cbc-623fefe2803c.png)
![image](https://user-images.githubusercontent.com/51820995/84739613-39f7d380-afac-11ea-985d-8ca7dca6d386.png)

**Comment by fredrikhgrelland** [comment]
This might fix it: https://www.nomadproject.io/docs/drivers/docker/#memory_hard_limit

**Comment by m88614** [comment]
Yeah, seems very useful. 

blocker https://github.com/fredrikhgrelland/vagrant-hashistack/issues/37

**Comment by fredrikhgrelland** [comment]
#88
