### ISSUE TITLE
make connect-to-xxx requires consul to be installed.

### ISSUE THREAD

**Issue by fredrikhgrelland** [fredrikhgrelland/data-mesh#93]
Pull consul from from vagrant image?

**Comment by m88614** [comment]
Not sure I understand. Are you talking about pulling the binary that is bundled with the vagrant box and adding it to the local machine?

**Comment by fredrikhgrelland** [comment]
Yes, maybe. It came up during a talk with eivind. He noted that it would not work if you didnt have consul binary in your path.
