### ISSUE TITLE
Add automatic update of box on make up

### ISSUE THREAD

**Issue by fredrikhgrelland** [fredrikhgrelland/data-mesh#95]
requires https://github.com/fredrikhgrelland/vagrant-hashistack/issues/43

**Comment by m88614** [comment]
Added a proposed solution to this in https://github.com/fredrikhgrelland/vagrant-hashistack/pull/47

**Comment by zhenik** [comment]
I think @fredrikhgrelland meant that once a user runs `make up` command, `up` target should first verify that the latest release of vagrant box is downloaded. 

Right now, the version update of the vagrant box `fredrikhgrelland/hashistack` is user responsibility.

**Comment by m88614** [comment]
Wait, were you supposed to answer for this issue? I asked what Fredrik meant in another issue, but not this one!
